# Generated by Django 5.2.7 on 2025-11-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryShop',
            new_name='ShopCategory',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ShopImage',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ShopProduct',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RenameField(
            model_name='shopcategory',
            old_name='name',
            new_name='name_Shop',
        ),
        migrations.RenameField(
            model_name='shopimage',
            old_name='image',
            new_name='image_Shop',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='description',
            new_name='description_Shop',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='images',
            new_name='images_Shop',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='in_stock',
            new_name='in_stock_Shop',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='name',
            new_name='name_Shop',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='price',
            new_name='price_Shop',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='category_Shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shopcategory'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
