# Generated by Django 5.2.7 on 2025-11-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_artist_genre_album_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='MusicAlbum',
        ),
        migrations.RenameModel(
            old_name='Artist',
            new_name='MusicArtist',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='MusicGenre',
        ),
        migrations.RenameModel(
            old_name='Song',
            new_name='MusicSong',
        ),
        migrations.RenameField(
            model_name='musicalbum',
            old_name='artist',
            new_name='artist_music',
        ),
        migrations.RenameField(
            model_name='musicalbum',
            old_name='cover',
            new_name='cover_music',
        ),
        migrations.RenameField(
            model_name='musicalbum',
            old_name='release_year',
            new_name='release_year_music',
        ),
        migrations.RenameField(
            model_name='musicalbum',
            old_name='title',
            new_name='title_music',
        ),
        migrations.RenameField(
            model_name='musicartist',
            old_name='date',
            new_name='date_music',
        ),
        migrations.RenameField(
            model_name='musicartist',
            old_name='image',
            new_name='image_music',
        ),
        migrations.RenameField(
            model_name='musicartist',
            old_name='name',
            new_name='name_music',
        ),
        migrations.RenameField(
            model_name='musicgenre',
            old_name='name',
            new_name='name_music',
        ),
        migrations.RenameField(
            model_name='musicsong',
            old_name='album',
            new_name='album_music',
        ),
        migrations.RenameField(
            model_name='musicsong',
            old_name='artist',
            new_name='artist_music',
        ),
        migrations.RenameField(
            model_name='musicsong',
            old_name='audio_file',
            new_name='audio_file_music',
        ),
        migrations.RenameField(
            model_name='musicsong',
            old_name='genre',
            new_name='genre_music',
        ),
        migrations.RenameField(
            model_name='musicsong',
            old_name='title',
            new_name='title_music',
        ),
    ]
