# Generated by Django 5.2.7 on 2025-11-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_album_musicalbum_rename_artist_musicartist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='images_Shop',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='image_Shop',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
